# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Movie.create(name: "The Nightmare Before Christmas", rating: 5)
Movie.create(name: "Titanic", rating: 5)
Movie.create(name: "Venom", rating: 4)
Movie.create(name: "A Quiet Place", rating: 5)
Movie.create(name: "Nobody's Fool", rating: 2)
Movie.create(name: "Suspiria", rating: 4)
Movie.create(name: "Hereditary", rating: 4)
Movie.create(name: "Office Space", rating: 5)
Movie.create(name: "Elf", rating: 4)
Movie.create(name: "Dawn of the Planet of the Apes", rating: 3)
Movie.create(name: "Secret life of Pets", rating: 4)
Movie.create(name: "Overlord", rating: 3)
Movie.create(name: "Wonder Woman", rating: 5)
Movie.create(name: "Bohemian Rhapsody", rating: 4)
Movie.create(name: "Ocean's 8", rating: 5)

Celebrity.create(name: "some celebs name", value: 0.273856, app_id: "main")
Celebrity.create(name: "some1 celebs name", value: 0.373856, app_id: "main")
Celebrity.create(name: "some 2celebs name", value: 0.473856, app_id: "main")
Celebrity.create(name: "some c3elebs name", value: 0.573856, app_id: "main")
Celebrity.create(name: "some ce4lebs name", value: 0.673856, app_id: "main")
Celebrity.create(name: "some cel53ebs name", value: 0.773856, app_id: "main")
Celebrity.create(name: "some cele43bs name", value: 0.873856, app_id: "main")
Celebrity.create(name: "some celebs65 name", value: 0.973856, app_id: "main")
Celebrity.create(name: "some celebs 76name", value: 0.173856, app_id: "main")
Celebrity.create(name: "some celebs na5me", value: 0.6743856, app_id: "main")
Celebrity.create(name: "some celebs na7me", value: 0.273856, app_id: "main")
Celebrity.create(name: "some celebs nam5e", value: 0.0673856, app_id: "main")
